### ISSUE TITLE
Problema ao resolver dependência generic-auto-crud:0.0.5

### ISSUE THREAD

**Issue by JacintoErnesto** [ISYS-Dcore/generic-auto-crud#1]
Estou enfrentando um problema ao tentar construir o projeto, especificamente com a dependência io.github.isys-dcore:generic-auto-crud:jar:0.0.5. O Maven não consegue encontrar a versão mencionada no repositório central.
![Captura de ecrã de 2024-10-14 15-13-48](https://github.com/user-attachments/assets/f95088dd-b4b6-4318-bbaf-f582010e6d52)

**Comment by Domingos-Masta** [comment]
Boas chefe, após alguma análise, percebemos que para importar os componentes hospedados em pacotes no github precisar de ter as credenciais no teu ficheiro pom.xml, o que pode ser complexo e desnecessário pois convem que sejam anonimas as bibliotecas que usamos, por este motivo estamos a publicar a biblioteca diretamente no repositório central do maven, assim eliminamos esta necessidade.

Enquanto aguarda poderá implementar uma alternativa, sugerimos que baixe o jar e adicione manualmente para o seu repositório maven local e em seguida o consuma por ali. 

Informarei tão logo a lib esteja disponível no maven e fechacrei a issue.

**Comment by Domingos-Masta** [comment]
Boas chefe, problema resolvido use por favor a v0.0.6

```
<dependency>
    <groupId>io.github.isys-dcore</groupId>
    <artifactId>generic-auto-crud</artifactId>
    <version>0.0.6</version>
</dependency>
```

**Comment by JacintoErnesto** [comment]
Feito prof, darei continuidade com a implementação
